name: Feature request
description: Suggest an idea for this project
title: 'Feature request: '
labels: enhancement
body:
  - type: textarea
    id: formulation
    attributes:
      label: Please describe, is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: |
        I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
